resources:
- repo: self

pool:
  name: Hosted Ubuntu 1604
steps:
- bash: |
   curl -L https://github.com/filipw/dotnet-script/releases/download/0.28.0/dotnet-script.0.28.0.zip > dotnet-script.zip
   unzip -o dotnet-script.zip -d ./
  displayName: 'Install latest otnet-script'

- bash: 'dotnet dotnet-script/dotnet-script.dll build/build.csx'
  displayName: 'Run build.csx'
  env:
    IS_SECURE_BUILDENVIRONMENT: $(IS_SECURE_BUILDENVIRONMENT)
    GITHUB_REPO_TOKEN: $(GITHUB_REPO_TOKEN)
    NUGET_APIKEY: $(NUGET_APIKEY)

