<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Bernhard Richter</Authors>
    <PackageProjectUrl>https://github.com/seesharper/ResourceReader</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/seesharper/ResourceReader</RepositoryUrl>
    <PackageLicenseUrl>http://opensource.org/licenses/MIT</PackageLicenseUrl>
    <Copyright>Bernhard Richter</Copyright>
    <PackageTags>C# resource resources</PackageTags>
    <Description>Provides strongly typed access to embedded text files</Description>
  </PropertyGroup>

</Project>